using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Application.Dtos.Plans;

/// <summary>Complete plan output generated by the Coordinator Agent.</summary>
public record CoordinatorPlanResponse
{
    /// <summary>Planning service categories, such as Venue or Catering.</summary>
    [JsonPropertyName("serviceCategories")]
    public List<string> ServiceCategories { get; init; } = [];

    /// <summary>Recommended budget by service category.</summary>
    [JsonPropertyName("budgetAllocation")]
    public Dictionary<string, decimal> BudgetAllocation { get; init; } = [];

    /// <summary>Vendor categories to research, without specific vendor names.</summary>
    [JsonPropertyName("targetVendorTypes")]
    public List<string> TargetVendorTypes { get; init; } = [];

    /// <summary>Planning phases and their recommended timing.</summary>
    [JsonPropertyName("proposedTimeline")]
    public Dictionary<string, string> ProposedTimeline { get; init; } = [];

    /// <summary>Optional explanation of the generated plan.</summary>
    [JsonPropertyName("rationale")]
    public string? Rationale { get; init; }

    /// <summary>Risks identified by the Coordinator Agent.</summary>
    [JsonPropertyName("identifiedRisks")]
    public List<RiskDto> IdentifiedRisks { get; init; } = [];

    /// <summary>Information still needed before the plan is complete.</summary>
    [JsonPropertyName("missingRequirements")]
    public List<MissingRequirementDto> MissingRequirements { get; init; } = [];

    /// <summary>Completeness score from 0 to 100.</summary>
    [JsonPropertyName("planCompletenessScore")]
    [Range(0, 100)]
    public int PlanCompletenessScore { get; init; }

    /// <summary>Optional human-readable validation result.</summary>
    [JsonPropertyName("validationSummary")]
    public string? ValidationSummary { get; init; }

    /// <summary>Returns validation errors, optionally using the event budget and known vendor names.</summary>
    public IEnumerable<ValidationResult> GetValidationErrors(
        decimal? eventBudget = null,
        IEnumerable<string>? vendorNames = null)
    {
        if (ServiceCategories.Count == 0 || ServiceCategories.Any(string.IsNullOrWhiteSpace))
            yield return new ValidationResult(
                "At least one non-empty service category is required.",
                [nameof(ServiceCategories)]);

        if (BudgetAllocation.Any(item => string.IsNullOrWhiteSpace(item.Key) || item.Value < 0))
            yield return new ValidationResult(
                "Budget allocation keys must be non-empty and amounts cannot be negative.",
                [nameof(BudgetAllocation)]);

        if (eventBudget is < 0 || (eventBudget.HasValue && BudgetAllocation.Values.Sum() > eventBudget.Value))
            yield return new ValidationResult(
                "Budget allocation cannot exceed the event budget.",
                [nameof(BudgetAllocation)]);

        if (PlanCompletenessScore is < 0 or > 100)
            yield return new ValidationResult(
                "Plan completeness score must be between 0 and 100.",
                [nameof(PlanCompletenessScore)]);

        var names = vendorNames?
            .Where(name => !string.IsNullOrWhiteSpace(name))
            .ToArray() ?? [];
        foreach (var risk in IdentifiedRisks)
        {
            foreach (var error in risk.GetValidationErrors())
                yield return error;

            if (names.Any(name =>
                    !string.IsNullOrWhiteSpace(risk.Recommendation) &&
                    risk.Recommendation.Contains(name, StringComparison.OrdinalIgnoreCase)))
                yield return new ValidationResult(
                    "Recommendations must not contain specific vendor names.",
                    [nameof(IdentifiedRisks)]);
        }

        foreach (var requirement in MissingRequirements)
            foreach (var error in requirement.GetValidationErrors())
                yield return error;
    }

    /// <summary>Returns whether this response passes all available DTO-level checks.</summary>
    public bool IsValid(decimal? eventBudget = null, IEnumerable<string>? vendorNames = null) =>
        !GetValidationErrors(eventBudget, vendorNames).Any();
}
